SELECT * FROM dbo.Blinkit_data;

UPDATE Blinkit_data
SET Item_Fat_Content = 
CASE
WHEN Item_Fat_Content IN ('low fat','LF') THEN 'Low Fat'
WHEN Item_Fat_Content =  'reg' THEN 'Regular'
ELSE Item_Fat_Content
END;

--- CHECK Distenct values of Item_Fat_Content column
SELECT DISTINCT Item_Fat_Content, COUNT(*) AS COUNT_ORDER FROM dbo.Blinkit_data
GROUP BY Item_Fat_Content
ORDER BY COUNT(*) ASC;


---KPI'S Requirement
--- 1. Total Sales- The overall revenue generated by items sold
SELECT ROUND(SUM(Sales)/1000000,2) FROM dbo.Blinkit_data;
SELECT CAST(SUM(Sales)/1000000 AS DECIMAL(10,2)) AS Total_Sales FROM dbo.Blinkit_data;

---2. Average Sales The AVG revenue per sale
SELECT CAST(AVG(Sales) AS DECIMAL(10,2)) AS AVG_SAL FROM dbo.Blinkit_data;
---3. Number of item : The total count of different items sold
SELECT COUNT(Item_Fat_Content) AS Number_of_item FROM Blinkit_data;
---4. Average Rating : The avg Customer rating for items sold
SELECT ROUND(AVG(Rating),2) AS Avg_Rating FROM dbo.Blinkit_data;


--- 1. Total saleS by fat content
SELECT  
Item_Fat_Content,
CAST(CAST(SUM(Sales)/1000 AS DECIMAL(10,2)) AS VARCHAR) + 'K' AS Total_sal_by_Fat_in_thousand
,CAST(AVG(Sales) AS DECIMAL(10,2)) AS Avg_sal_by_Fat,
CAST(COUNT(Item_Fat_Content) AS DECIMAL(10,2)) AS Total_item_by_Fat,
CAST(AVG(Rating) AS DECIMAL(10,2)) AS AVG_rating_by_Fat
FROM dbo.Blinkit_data
GROUP BY Item_Fat_Content
;
---
---2. Total by items
SELECT  
TOP 5 Item_Type,
CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_sal_in_thousand,
CAST(AVG(Sales) AS DECIMAL(10,2)) AS Avg_sal,
CAST(COUNT(Item_Fat_Content) AS DECIMAL(10,2)) AS Total_item,
CAST(AVG(Rating) AS DECIMAL(10,2)) AS AVG_rating
FROM dbo.Blinkit_data
GROUP BY Item_Type
ORDER BY Total_sal_in_thousand DESC;

---Make a pivot table for Low Fat And Regular
SELECT Outlet_Location_Type,
       ISNULL([Low Fat],0) AS Low_Fat,
	   ISNULL([Regular],0) AS Regular
FROM
     (SELECT Outlet_Location_Type,Item_Fat_Content,
	 CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_Sales
  FROM dbo.Blinkit_data
  GROUP BY  Outlet_Location_Type,Item_Fat_Content
  )AS Source_Tables
  PIVOT
  (
     SUM(Total_Sales)
   FOR Item_Fat_Content IN ([Low Fat], [Regular])
  ) AS PivotTable
  ORDER BY Outlet_Location_Type;
	 
--- FIND TOTAL SALES BY Outlet_Establishment_Year

SELECT  
Outlet_Establishment_Year,
CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_sal_in_thousand,
CAST(AVG(Sales) AS DECIMAL(10,2)) AS Avg_sal,
CAST(COUNT(Item_Fat_Content) AS DECIMAL(10,2)) AS Total_item,
CAST(AVG(Rating) AS DECIMAL(10,2)) AS AVG_rating
FROM dbo.Blinkit_data
GROUP BY Outlet_Establishment_Year
ORDER BY Outlet_Establishment_Year ASC;

---FIND Outlet_Size BY SALES PERCENT.
SELECT Outlet_Size,
CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_Sales,
CAST((SUM(Sales)*100/SUM(SUM(Sales)) OVER()) AS DECIMAL(10,2)) AS Percent_sales	
FROM dbo.Blinkit_data
GROUP BY Outlet_Size
ORDER BY Total_Sales DESC;

---find Outlet_Location_Type by sales percentage
SELECT Outlet_Location_Type,
CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_Sales,
CAST((SUM(Sales)*100/SUM(SUM(Sales)) OVER()) AS DECIMAL(10,2)) AS Percent_sales	,
CAST(AVG(Sales) AS DECIMAL(10,2)) AS Avg_sal,
CAST(COUNT(Item_Fat_Content) AS DECIMAL(10,2)) AS Total_item,
CAST(AVG(Rating) AS DECIMAL(10,2)) AS AVG_rating
FROM dbo.Blinkit_data
GROUP BY Outlet_Location_Type
ORDER BY Total_Sales DESC;

---
SELECT Outlet_Type,
CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_Sales,
CAST((SUM(Sales)*100/SUM(SUM(Sales)) OVER()) AS DECIMAL(10,2)) AS Percent_sales	,
CAST(AVG(Sales) AS DECIMAL(10,2)) AS Avg_sal,
CAST(COUNT(Item_Fat_Content) AS DECIMAL(10,2)) AS Total_item,
CAST(AVG(Rating) AS DECIMAL(10,2)) AS AVG_rating
FROM dbo.Blinkit_data
GROUP BY Outlet_Type
ORDER BY Total_Sales DESC;




